return function(colors)
    return {
        BlinkCmpMenu                = { fg = colors.disabled },
        BlinkCmpMenuBorder          = { fg = colors.background_darker, bg = colors.background },
        BlinkCmpMenuSelection       = { bg = colors.selection },
        BlinkCmpLabel               = { fg = colors.foreground },
        BlinkCmpGhostText           = { fg = '#414868' },
        BlinkCmpLabelMatch          = { fg = colors.orange, bold = true },
        BlinkCmpLabelDetail         = { link = "BlinkCmpLabel" },
        BlinkCmpLabelDescription    = { link = "BlinkCmpLabel" },
        BlinkCmpSource              = { fg = colors.disabled },
        BlinkCmpDocBorder           = { link = "BlinkCmpMenuBorder" },
        BlinkCmpSignatureHelpBorder = { link = "BlinkCmpMenuBorder" },
        BlinkCmpLabelDeprecated     = { fg = colors.foreground_darker, strikethrough = true },
        BlinkCmpKind                = { fg = colors.blue },
        BlinkCmpKindText            = { fg = colors.comments },
        BlinkCmpKindMethod          = { fg = colors.blue },
        BlinkCmpKindFunction        = { fg = colors.blue },
        BlinkCmpKindContructor      = { fg = colors.blue },
        BlinkCmpKindField           = { fg = colors.cyan },
        BlinkCmpKindVariable        = { fg = colors.paleblue },
        BlinkCmpKindValue           = { fg = colors.paleblue },
        BlinkCmpKindConstant        = { fg = colors.yellow },
        BlinkCmpKindClass           = { fg = colors.yellow },
        BlinkCmpKindStruct          = { fg = colors.yellow },
        BlinkCmpKindInterface       = { fg = colors.yellow },
        BlinkCmpKindModule          = { fg = colors.orange },
        BlinkCmpKindProperty        = { fg = colors.purple },
        BlinkCmpKindKeyword         = { fg = colors.purple },
        BlinkCmpKindUnit            = { fg = colors.green },
        BlinkCmpKindFile            = { fg = colors.yellow },
        BlinkCmpKindFolder          = { fg = colors.yellow },
        BlinkCmpKindSnippet         = { fg = colors.green },
        BlinkCmpKindEvent           = { fg = colors.blue },
        BlinkCmpKindTypeParameter   = { fg = colors.blue },
        BlinkCmpKindCopilot         = { fg = colors.dark_blue },
        BlinkCmpKindColor           = { fg = colors.red },
    }
end
