return function(colors)
    return {
        CmpDocumentation         = { bg = colors.background_darker },
        CmpItemAbbrDefault       = { fg = colors.foreground },
        CmpItemAbbr              = { fg = colors.foreground },
        CmpItemAbbrDeprecated    = { fg = colors.foreground_darker, strikethrough = true },
        CmpItemAbbrMatch         = { fg = colors.blue },
        CmpItemAbbrMatchFuzzy    = { fg = colors.blue },
        CmpItemMenu              = { fg = colors.comments },
        CmpItemKindDefault       = { fg = colors.foreground_darker },
        CmpItemKindKeyword       = { fg = colors.purple },
        CmpItemKindReference     = { fg = colors.purple },
        CmpItemKindValue         = { fg = colors.purple },
        CmpItemKindVariable      = { fg = colors.purple },
        CmpItemKindConstant      = { fg = colors.orange },
        CmpItemKindEnum          = { fg = colors.orange },
        CmpItemKindEnumMember    = { fg = colors.orange },
        CmpItemKindOperator      = { fg = colors.orange },
        CmpItemKindField         = { fg = colors.orange },
        CmpItemKindFunction      = { fg = colors.blue },
        CmpItemKindMethod        = { fg = colors.blue },
        CmpItemKindConstructor   = { fg = colors.yellow },
        CmpItemKindClass         = { fg = colors.yellow },
        CmpItemKindInterface     = { fg = colors.yellow },
        CmpItemKindStruct        = { fg = colors.yellow },
        CmpItemKindEvent         = { fg = colors.yellow },
        CmpItemKindUnit          = { fg = colors.yellow },
        CmpItemKindFile          = { fg = colors.yellow },
        CmpItemKindFolder        = { fg = colors.yellow },
        CmpItemKindModule        = { fg = colors.green },
        CmpItemKindProperty      = { fg = colors.green },
        CmpItemKindTypeParameter = { fg = colors.green },
        CmpItemKindSnippet       = { fg = colors.green },
        CmpItemKindText          = { fg = colors.green },
    }
end
