return function(colors)
    return {
        DevIconC        = { fg = colors.cyan },
        DevIconCpp      = { fg = colors.cyan },
        DevIconGo       = { fg = colors.cyan },
        DevIconTs       = { fg = colors.cyan },
        DevIconLua      = { fg = colors.blue },
        DevIconDart     = { fg = colors.blue },
        DevIconJs       = { fg = colors.yellow },
        DevIconPy       = { fg = colors.yellow },
        DevIconCss      = { fg = colors.yellow },
        DevIconJson     = { fg = colors.yellow },
        DevIconJava     = { fg = colors.red },
        DevIconRb       = { fg = colors.red },
        DevIconRs       = { fg = colors.red },
        DevIconMd       = { fg = colors.red },
        DevIconHtml     = { fg = colors.red },
        DevIconMakefile = { fg = colors.red },
        DevIconRed      = { fg = colors.red },
        DevIconHs       = { fg = colors.purple },
        DevIconPhp      = { fg = colors.purple },
        DevIconH        = { fg = colors.purple },
        DevIconSh       = { fg = colors.green },
        DevIconBash     = { fg = colors.green },
        DevIconVim      = { fg = colors.green },
        DevIconVue      = { fg = colors.green },
        DevIconTerminal = { fg = colors.green },
        DevIconDiff     = { fg = colors.orange },
        DevIconConf     = { fg = colors.orange },
        DevIconToml     = { fg = colors.orange },
        DevIconKotlin   = { fg = colors.orange },
        DevIconSwift    = { fg = colors.orange },
    }
end
